from __future__ import annotations

import json
from io import StringIO
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, inspect, text
from sqlalchemy.exc import IntegrityError

from cf_agent_gateway import migration
from cf_agent_gateway.database import (
    Base,
    create_database_engine,
    initialize_database,
    load_database_models,
)

ALEMBIC_CONFIG_PATH = Path(__file__).resolve().parents[1] / "alembic.ini"
LEGACY_BUSINESS_TABLES = frozenset(
    {
        "ai_threads",
        "attachments",
        "conversations",
        "employee_workspaces",
        "enterprise_identities",
        "gateway_access_policies",
        "messages",
        "source_identity_mappings",
        "thread_source_bindings",
        "user_access_policies",
        "wechat_sync_checkpoints",
    }
)
ARCHIVE_TABLES = frozenset({"message_delivery_attempts", "message_raw_payloads"})
PROFILE_TABLES = frozenset(
    {
        "agent_profiles",
        "conversation_group_type_bindings",
        "group_types",
    }
)
PRE_PROFILE_TABLES = LEGACY_BUSINESS_TABLES | ARCHIVE_TABLES
PROFILE_SCHEMA_TABLES = PRE_PROFILE_TABLES | PROFILE_TABLES
OUTBOX_TABLES = frozenset({"hermes_dispatch_records"})
OUTBOX_SCHEMA_TABLES = PROFILE_SCHEMA_TABLES | OUTBOX_TABLES
ARTIFACT_TABLES = frozenset({"artifacts"})
ARTIFACT_SCHEMA_TABLES = OUTBOX_SCHEMA_TABLES | ARTIFACT_TABLES
ROUTING_TABLES = frozenset({"conversation_agent_profile_bindings"})
WORKER_TABLES = frozenset({"hermes_dispatch_responses"})
RESPONSE_DELIVERY_TABLES = frozenset(
    {
        "hermes_responses",
        "hermes_response_parts",
        "delivery_outbox",
        "delivery_attempts",
        "delivery_receipts",
    }
)
SCHEMA_TABLES = ARTIFACT_SCHEMA_TABLES | ROUTING_TABLES | WORKER_TABLES | RESPONSE_DELIVERY_TABLES
FOUNDATION_REVISION = "20260806_01"
ARCHIVE_REVISION = "20260806_0002"
PROFILE_REVISION = "20260806_02"
OUTBOX_REVISION = "20260806_03"
ARTIFACT_REVISION = "20260806_04"
ROUTING_REVISION = "20260807_01"
WORKER_REVISION = "20260807_02"
RESPONSE_DELIVERY_REVISION = "20260807_03"


def _head_revision() -> str:
    migration_config = migration.create_migration_config()
    head_revision = ScriptDirectory.from_config(migration_config).get_current_head()
    assert head_revision == RESPONSE_DELIVERY_REVISION
    return head_revision


def _upgrade_to_archive_schema(engine: Engine) -> None:
    migration.upgrade_database(engine, ARCHIVE_REVISION)


def test_model_metadata_has_expected_business_tables() -> None:
    load_database_models()

    assert set(Base.metadata.tables) == SCHEMA_TABLES


def test_upgrade_preserves_foundation_marker_then_applies_schema_chain() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        assert migration.get_schema_version(engine) is None

        migration.upgrade_database(engine, FOUNDATION_REVISION)

        assert set(inspect(engine).get_table_names()) == {"alembic_version"}
        assert migration.get_schema_version(engine) == FOUNDATION_REVISION

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == _head_revision()

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == _head_revision()
    finally:
        engine.dispose()


def test_upgrade_preserves_existing_tables_and_data() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        with engine.begin() as connection:
            connection.execute(text("CREATE TABLE existing_data (id INTEGER PRIMARY KEY)"))
            connection.execute(text("INSERT INTO existing_data (id) VALUES (7)"))

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {
            "alembic_version",
            "existing_data",
        }
        with engine.connect() as connection:
            assert connection.scalar(text("SELECT id FROM existing_data")) == 7
    finally:
        engine.dispose()


def test_upgrade_is_idempotent_after_database_initialization() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        initialize_database(engine)
        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == _head_revision()
    finally:
        engine.dispose()


def test_upgrade_adds_profile_tables_to_archive_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        _upgrade_to_archive_schema(engine)
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO conversations "
                    "(source, source_account_id, conversation_id, conversation_type) "
                    "VALUES ('wechat', 'bot-001', 'group-001', 'group')"
                )
            )
        assert set(inspect(engine).get_table_names()) == PRE_PROFILE_TABLES | {"alembic_version"}

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == _head_revision()
        with engine.connect() as connection:
            assert connection.scalar(text("SELECT conversation_id FROM conversations")) == (
                "group-001"
            )
            assert (
                connection.scalar(
                    text(
                        "SELECT count(*) FROM sqlite_master "
                        "WHERE type = 'trigger' "
                        "AND name = 'trg_agent_profiles_immutable_revision'"
                    )
                )
                == 1
            )
    finally:
        engine.dispose()


def test_migrate_database_creates_file_sqlite_parent_and_persists_version(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "nested" / "gateway.db"
    database_url = f"sqlite+pysqlite:///{database_path.as_posix()}"

    schema_version = migration.migrate_database(database_url)

    assert database_path.is_file()
    assert schema_version == _head_revision()
    engine = create_database_engine(database_url)
    try:
        assert migration.get_schema_version(engine) == _head_revision()
        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
    finally:
        engine.dispose()


def test_postgresql_offline_upgrade_emits_complete_schema_ddl() -> None:
    output = StringIO()
    migration_config = Config(str(ALEMBIC_CONFIG_PATH), output_buffer=output)
    migration_config.attributes["database_url"] = (
        "postgresql+psycopg://user:password@localhost/gateway"
    )

    command.upgrade(migration_config, "head", sql=True)

    rendered_sql = output.getvalue().lower()
    assert "create table alembic_version" in rendered_sql
    assert _head_revision().lower() in rendered_sql
    assert all(table_name in rendered_sql for table_name in SCHEMA_TABLES)
    assert "create or replace function guard_agent_profile_revision_immutable" in rendered_sql
    assert "before update or delete on agent_profiles" in rendered_sql
    assert "uq_hermes_dispatch_idempotency_key" in rendered_sql
    assert "uq_hermes_dispatch_message" in rendered_sql
    assert "ck_hermes_dispatch_state_fields" in rendered_sql
    assert "ix_hermes_dispatch_thread_queue" in rendered_sql
    assert "lease_expires_at" in rendered_sql
    assert "uq_hermes_dispatch_running_thread" in rendered_sql
    assert "ix_hermes_dispatch_claim" in rendered_sql
    assert "create table hermes_dispatch_responses" in rendered_sql
    assert "uq_artifact_storage_key" in rendered_sql
    assert "artifact_kind" in rendered_sql
    assert "artifact_status" in rendered_sql
    assert "ck_artifact_ready_metadata" in rendered_sql
    assert "ck_artifact_size_nonnegative" in rendered_sql
    assert "ix_artifact_response_id" in rendered_sql
    assert "uq_conversation_agent_profile_binding_conversation" in rendered_sql
    assert "ck_ai_thread_v2_route_snapshot" in rendered_sql
    assert "ck_ai_thread_v2_thread_policy" in rendered_sql
    assert "ck_ai_thread_v2_policy_matches_type" in rendered_sql
    assert "fk_ai_thread_agent_profile" in rendered_sql
    assert "ix_ai_threads_agent_profile_id" in rendered_sql
    normalized_sql = " ".join(rendered_sql.split())
    assert "alter table messages add column direction varchar(16)" in normalized_sql
    assert "alter table messages add column occurred_at timestamp with time zone" in normalized_sql
    assert "alter table messages add column received_at timestamp with time zone" in normalized_sql
    assert "when sender_type = 'system' then 'system'" in normalized_sql
    assert "when is_self then 'outbound'" in normalized_sql
    assert "alter table messages alter column direction set not null" in normalized_sql
    assert "alter table messages alter column occurred_at set not null" in normalized_sql
    assert "alter table messages alter column received_at set not null" in normalized_sql
    assert "constraint ck_message_direction" in normalized_sql
    assert "foreign key(message_id) references messages (id) on delete restrict" in normalized_sql
    assert (
        "foreign key(enterprise_identity_id) references enterprise_identities (id) "
        "on delete restrict"
    ) in normalized_sql
    assert "foreign key(workspace_id) references employee_workspaces (id)" in normalized_sql
    assert "foreign key(ai_thread_id) references ai_threads (id)" in normalized_sql


def test_sqlite_online_upgrade_applies_batch_migration(tmp_path: Path) -> None:
    database_path = tmp_path / "batch.db"
    database_url = f"sqlite+pysqlite:///{database_path.as_posix()}"
    migration_config = Config(str(ALEMBIC_CONFIG_PATH))
    migration_config.attributes["configure_logger"] = False
    migration_config.set_main_option("sqlalchemy.url", database_url)

    command.upgrade(migration_config, "20260806_0001")

    engine = create_database_engine(database_url)
    try:
        baseline_columns = {column["name"] for column in inspect(engine).get_columns("messages")}
        assert {"direction", "occurred_at", "received_at"}.isdisjoint(baseline_columns)
    finally:
        engine.dispose()

    command.upgrade(migration_config, "head")

    engine = create_database_engine(database_url)
    try:
        inspector = inspect(engine)
        archive_columns = {column["name"] for column in inspector.get_columns("messages")}
        assert {"direction", "occurred_at", "received_at"}.issubset(archive_columns)
        assert {"message_delivery_attempts", "message_raw_payloads"}.issubset(
            inspector.get_table_names()
        )
        assert "ck_message_direction" in {
            constraint["name"] for constraint in inspector.get_check_constraints("messages")
        }
        assert PROFILE_TABLES.issubset(inspector.get_table_names())
        assert OUTBOX_TABLES.issubset(inspector.get_table_names())
        dispatch_checks = {
            constraint["name"]
            for constraint in inspector.get_check_constraints("hermes_dispatch_records")
        }
        assert dispatch_checks >= {
            "ck_hermes_dispatch_nonempty_claim_token",
            "ck_hermes_dispatch_nonempty_error_code",
            "ck_hermes_dispatch_nonempty_idempotency_key",
            "ck_hermes_dispatch_nonnegative_attempt_count",
            "ck_hermes_dispatch_state_fields",
            "ck_hermes_dispatch_status",
            "ck_hermes_dispatch_status_attempt_count",
        }
        dispatch_indexes = {
            index["name"] for index in inspector.get_indexes("hermes_dispatch_records")
        }
        assert dispatch_indexes >= {
            "ix_hermes_dispatch_queue",
            "ix_hermes_dispatch_records_message_id",
            "ix_hermes_dispatch_thread_queue",
            "ix_hermes_dispatch_claim",
            "ix_hermes_dispatch_fifo",
            "uq_hermes_dispatch_running_thread",
        }
        assert ARTIFACT_TABLES.issubset(inspector.get_table_names())
        artifact_checks = {
            constraint["name"] for constraint in inspector.get_check_constraints("artifacts")
        }
        assert artifact_checks >= {
            "artifact_kind",
            "artifact_status",
            "ck_artifact_ready_metadata",
            "ck_artifact_size_nonnegative",
        }
        assert {
            constraint["name"] for constraint in inspector.get_unique_constraints("artifacts")
        } >= {"uq_artifact_storage_key"}
        assert {index["name"] for index in inspector.get_indexes("artifacts")} >= {
            "ix_artifact_response_id"
        }
        assert ROUTING_TABLES.issubset(inspector.get_table_names())
        ai_thread_columns = {column["name"] for column in inspector.get_columns("ai_threads")}
        assert {"agent_profile_id", "thread_policy"}.issubset(ai_thread_columns)
        assert {
            constraint["name"] for constraint in inspector.get_check_constraints("ai_threads")
        } >= {
            "ck_ai_thread_v2_route_snapshot",
            "ck_ai_thread_v2_thread_policy",
            "ck_ai_thread_v2_policy_matches_type",
        }
        assert {
            constraint["name"]
            for constraint in inspector.get_unique_constraints(
                "conversation_agent_profile_bindings"
            )
        } >= {"uq_conversation_agent_profile_binding_conversation"}
        assert {
            index["name"] for index in inspector.get_indexes("conversation_agent_profile_bindings")
        } >= {
            "ix_conversation_agent_profile_bindings_agent_profile_id",
            "ix_conversation_agent_profile_bindings_conversation_id",
        }
        assert {index["name"] for index in inspector.get_indexes("ai_threads")} >= {
            "ix_ai_threads_agent_profile_id"
        }
        with engine.connect() as connection:
            triggers = set(
                connection.scalars(text("SELECT name FROM sqlite_master WHERE type = 'trigger'"))
            )
        assert {
            "trg_agent_profiles_immutable_revision",
            "trg_agent_profiles_prevent_delete",
        }.issubset(triggers)
        assert migration.get_schema_version(engine) == _head_revision()
    finally:
        engine.dispose()


def test_migrated_schema_has_no_alembic_drift() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine)
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.check(migration_config)
    finally:
        engine.dispose()


def test_alembic_check_reports_schema_drift() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        initialize_database(engine)
        with engine.begin() as connection:
            connection.execute(text("ALTER TABLE artifacts ADD COLUMN unexpected_value TEXT"))

        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            with pytest.raises(AutogenerateDiffsDetected, match="New upgrade operations"):
                command.check(migration_config)
    finally:
        engine.dispose()


def test_upgrade_adopts_profile_schema_created_by_sqlalchemy() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        _upgrade_to_archive_schema(engine)
        load_database_models()
        profile_tables = [
            table for table in Base.metadata.sorted_tables if table.name in PROFILE_TABLES
        ]
        Base.metadata.create_all(engine, tables=profile_tables)
        assert set(inspect(engine).get_table_names()) == PROFILE_SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == ARCHIVE_REVISION

        migration.upgrade_database(engine)

        assert set(inspect(engine).get_table_names()) == SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == _head_revision()
        with engine.connect() as connection:
            assert (
                connection.scalar(
                    text(
                        "SELECT count(*) FROM sqlite_master "
                        "WHERE type = 'trigger' "
                        "AND name = 'trg_agent_profiles_immutable_revision'"
                    )
                )
                == 1
            )
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.check(migration_config)
    finally:
        engine.dispose()


def test_application_initialization_after_empty_upgrade_installs_revision_guard() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine)
        initialize_database(engine)
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO agent_profiles "
                    "(id, profile_key, revision, provider, external_profile_ref, model) "
                    "VALUES ('profile-1', 'assistant', 1, 'openai', 'external-1', 'gpt-5.2')"
                )
            )

        with (
            pytest.raises(IntegrityError, match="agent profile revision is immutable"),
            engine.begin() as connection,
        ):
            connection.execute(
                text("UPDATE agent_profiles SET model = 'overwritten' WHERE id = 'profile-1'")
            )

        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.check(migration_config)
    finally:
        engine.dispose()


def test_upgrade_rejects_partial_v2_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        _upgrade_to_archive_schema(engine)
        load_database_models()
        Base.metadata.tables["agent_profiles"].create(engine)

        with pytest.raises(RuntimeError, match="partial Agent Profile and Group Type schema"):
            migration.upgrade_database(engine)
    finally:
        engine.dispose()


def test_downgrade_removes_only_profile_configuration_tables() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine, PROFILE_REVISION)
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO conversations "
                    "(source, source_account_id, conversation_id, conversation_type) "
                    "VALUES ('wechat', 'bot-001', 'group-001', 'group')"
                )
            )
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.downgrade(migration_config, ARCHIVE_REVISION)

        assert set(inspect(engine).get_table_names()) == PRE_PROFILE_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == ARCHIVE_REVISION
        with engine.connect() as connection:
            assert connection.scalar(text("SELECT conversation_id FROM conversations")) == (
                "group-001"
            )
    finally:
        engine.dispose()


def test_fresh_database_profile_downgrade_preserves_archive_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine, PROFILE_REVISION)
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.downgrade(migration_config, ARCHIVE_REVISION)

        assert set(inspect(engine).get_table_names()) == PRE_PROFILE_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == ARCHIVE_REVISION
    finally:
        engine.dispose()


def test_outbox_downgrade_preserves_profile_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine, OUTBOX_REVISION)
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.downgrade(migration_config, PROFILE_REVISION)

        assert set(inspect(engine).get_table_names()) == PROFILE_SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == PROFILE_REVISION
    finally:
        engine.dispose()


def test_artifact_downgrade_preserves_outbox_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine)
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.downgrade(migration_config, OUTBOX_REVISION)

        assert set(inspect(engine).get_table_names()) == OUTBOX_SCHEMA_TABLES | {"alembic_version"}
        assert migration.get_schema_version(engine) == OUTBOX_REVISION
    finally:
        engine.dispose()


def test_routing_downgrade_preserves_artifact_schema() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    try:
        migration.upgrade_database(engine)
        migration_config = migration.create_migration_config()
        with engine.connect() as connection:
            migration_config.attributes["connection"] = connection
            command.downgrade(migration_config, ARTIFACT_REVISION)

        inspector = inspect(engine)
        assert set(inspector.get_table_names()) == ARTIFACT_SCHEMA_TABLES | {"alembic_version"}
        assert {"agent_profile_id", "thread_policy"}.isdisjoint(
            {column["name"] for column in inspector.get_columns("ai_threads")}
        )
        assert migration.get_schema_version(engine) == ARTIFACT_REVISION
    finally:
        engine.dispose()


def test_migration_cli_reads_gateway_config(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    database_path = tmp_path / "cli" / "gateway.db"
    application_config_path = tmp_path / "config.yaml"
    application_config_path.write_text(
        f'database:\n  url: "sqlite+pysqlite:///{database_path.as_posix()}"\n',
        encoding="utf-8",
    )
    monkeypatch.setenv("CF_GATEWAY_CONFIG", str(application_config_path))
    monkeypatch.delenv("CF_GATEWAY_ALEMBIC_CONFIG", raising=False)
    monkeypatch.chdir(tmp_path)

    assert migration.main() == 0

    output = json.loads(capsys.readouterr().out)
    assert output == {"schema_version": _head_revision()}
    assert database_path.is_file()


def test_migration_cli_returns_sanitized_error(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    monkeypatch.setenv("CF_GATEWAY_CONFIG", str(tmp_path / "missing.yaml"))
    monkeypatch.delenv("CF_GATEWAY_ALEMBIC_CONFIG", raising=False)

    assert migration.main() == 1

    captured = capsys.readouterr()
    assert captured.out == ""
    assert json.loads(captured.err) == {"error_code": "database_migration_failed"}
