"""baseline main schema

Revision ID: 20260806_0001
Revises: 20260806_01
Create Date: 2026-08-06 16:54:24.872183
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op

revision: str = "20260806_0001"
down_revision: str | Sequence[str] | None = "20260806_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_MAIN_SCHEMA_TABLES = frozenset(
    {
        "ai_threads",
        "attachments",
        "conversations",
        "employee_workspaces",
        "enterprise_identities",
        "gateway_access_policies",
        "messages",
        "source_identity_mappings",
        "thread_source_bindings",
        "user_access_policies",
        "wechat_sync_checkpoints",
    }
)


def upgrade() -> None:
    if not _main_schema_needs_creation():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_account_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_type", sa.String(length=64), nullable=False),
        sa.Column("conversation_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source",
            "source_account_id",
            "conversation_id",
            name="uq_conversation_source_account_id",
        ),
    )
    op.create_table(
        "enterprise_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", "archived", name="identity_status", native_enum=False),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", name="uq_enterprise_identity_employee_id"),
    )
    op.create_table(
        "gateway_access_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("policy_key", sa.String(length=64), server_default="default", nullable=False),
        sa.Column("permission_scope", sa.JSON(), nullable=False),
        sa.Column("allowed_skills", sa.JSON(), nullable=False),
        sa.Column("allowed_risk_levels", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("policy_key = 'default'", name="ck_gateway_access_policy_default_key"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_key", name="uq_gateway_access_policy_key"),
    )
    op.create_table(
        "wechat_sync_checkpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_account_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("last_local_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "initialized_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "last_local_id >= 0", name="ck_wechat_sync_checkpoint_nonnegative_local_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_account_id",
            "conversation_id",
            name="uq_wechat_sync_checkpoint_account_conversation",
        ),
    )
    op.create_table(
        "employee_workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_identity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", "archived", name="workspace_status", native_enum=False),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_identity_id"], ["enterprise_identities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "enterprise_identity_id", name="uq_employee_workspace_enterprise_identity"
        ),
    )
    with op.batch_alter_table("employee_workspaces", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_workspaces_enterprise_identity_id"),
            ["enterprise_identity_id"],
            unique=False,
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_account_id", sa.String(length=255), nullable=False),
        sa.Column("source_message_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_type", sa.String(length=64), nullable=False),
        sa.Column("is_mentioned", sa.Boolean(), nullable=True),
        sa.Column("is_self", sa.Boolean(), nullable=False),
        sa.Column("sender_type", sa.String(length=16), nullable=False),
        sa.Column("sender_id", sa.String(length=255), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("message_type", sa.String(length=64), nullable=False),
        sa.Column("raw_type", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_local_id", sa.String(length=255), nullable=True),
        sa.Column("source_server_id", sa.String(length=255), nullable=True),
        sa.Column(
            "source_message_id_is_fallback", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column("reply_context", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("reply_to_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "(conversation_type != 'private' OR is_mentioned IS NULL) AND "
            "(conversation_type != 'group' OR is_mentioned IS NOT NULL)",
            name="ck_message_conversation_mention",
        ),
        sa.CheckConstraint(
            "sender_type = 'system' OR (sender_id IS NOT NULL AND length(trim(sender_id)) > 0)",
            name="ck_message_human_sender_id",
        ),
        sa.CheckConstraint("sender_type IN ('human', 'system')", name="ck_message_sender_type"),
        sa.ForeignKeyConstraint(
            ["source", "source_account_id", "conversation_id"],
            [
                "conversations.source",
                "conversations.source_account_id",
                "conversations.conversation_id",
            ],
            name="fk_message_conversation",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="uq_message_event_id"),
        sa.UniqueConstraint(
            "source",
            "source_account_id",
            "conversation_id",
            "source_message_id",
            name="uq_message_source_account_conversation_message",
        ),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_message_conversation_timestamp",
            ["source", "source_account_id", "conversation_id", "timestamp", "id"],
            unique=False,
        )

    op.create_table(
        "source_identity_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("sender_id", sa.String(length=255), nullable=False),
        sa.Column("enterprise_identity_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_identity_id"], ["enterprise_identities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "account_id", "sender_id", name="uq_source_identity_platform_account_sender"
        ),
    )
    with op.batch_alter_table("source_identity_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_identity_mappings_enterprise_identity_id"),
            ["enterprise_identity_id"],
            unique=False,
        )

    op.create_table(
        "user_access_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enterprise_identity_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("permission_scope", sa.JSON(), nullable=False),
        sa.Column("allowed_skills", sa.JSON(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["enterprise_identity_id"], ["enterprise_identities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "enterprise_identity_id", name="uq_user_access_policy_enterprise_identity"
        ),
    )
    with op.batch_alter_table("user_access_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_access_policies_enterprise_identity_id"),
            ["enterprise_identity_id"],
            unique=False,
        )

    op.create_table(
        "ai_threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column(
            "thread_type",
            sa.Enum("private", "group", name="thread_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("thread_key", sa.String(length=96), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", "archived", name="thread_status", native_enum=False),
            server_default="active",
            nullable=False,
        ),
        sa.Column("hermes_thread_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["employee_workspaces.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hermes_thread_id", name="uq_ai_thread_hermes_thread_id"),
        sa.UniqueConstraint("thread_key", name="uq_ai_thread_key"),
    )
    with op.batch_alter_table("ai_threads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_threads_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_message_id"), ["message_id"], unique=False)

    op.create_table(
        "thread_source_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ai_thread_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("physical_conversation_id", sa.String(length=255), nullable=False),
        sa.Column("sender_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["ai_thread_id"], ["ai_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "account_id", "physical_conversation_id", name="uq_thread_source_fact"
        ),
    )
    with op.batch_alter_table("thread_source_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thread_source_bindings_ai_thread_id"), ["ai_thread_id"], unique=False
        )

    # ### end Alembic commands ###


def _main_schema_needs_creation() -> bool:
    if context.is_offline_mode():
        return True

    existing_tables = set(sa.inspect(op.get_bind()).get_table_names()) - {"alembic_version"}
    if not existing_tables:
        return True
    missing_tables = _MAIN_SCHEMA_TABLES - existing_tables
    if not missing_tables:
        return False
    if existing_tables & _MAIN_SCHEMA_TABLES:
        missing = ", ".join(sorted(missing_tables))
        raise RuntimeError(f"cannot adopt partial main schema; missing tables: {missing}")
    return True


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_source_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_source_bindings_ai_thread_id"))

    op.drop_table("thread_source_bindings")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_message_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("ai_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_threads_workspace_id"))

    op.drop_table("ai_threads")
    with op.batch_alter_table("user_access_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_access_policies_enterprise_identity_id"))

    op.drop_table("user_access_policies")
    with op.batch_alter_table("source_identity_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_identity_mappings_enterprise_identity_id"))

    op.drop_table("source_identity_mappings")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_message_conversation_timestamp")

    op.drop_table("messages")
    with op.batch_alter_table("employee_workspaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_workspaces_enterprise_identity_id"))

    op.drop_table("employee_workspaces")
    op.drop_table("wechat_sync_checkpoints")
    op.drop_table("gateway_access_policies")
    op.drop_table("enterprise_identities")
    op.drop_table("conversations")
    # ### end Alembic commands ###
